### ISSUE TITLE
running problems.

### ISSUE THREAD

**Issue by PegX** [datafrick/tutorial#1]
I encounter the following problems when I run python3 fl_implemetation.py ./trainingSet/trainingSet
 got shape [3780, 784], but wanted [3780].
I try to figure out the problem, but that cannot work until now.
Would you mind give me some hints?

**Comment by stijani** [comment]
Hi PegX,

Please can your paste the full exception details here?

**Comment by PegX** [comment]
Traceback (most recent call last):
  File "fl_implemetation.py", line 53, in <module>
    clients_batched[client_name] = batch_data(data)
  File "/home/peng/Projects/federated_learning/tutorial/fl_mnist_implementation_tutorial_utils.py", line 86, in batch_data
    dataset = tf.data.Dataset.from_tensor_slices((list(data), list(label)))
  File "/home/peng/anaconda3/lib/python3.7/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 1685, in from_tensor_slices
    return DatasetV1Adapter(DatasetV2.from_tensor_slices(tensors))
  File "/home/peng/anaconda3/lib/python3.7/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 364, in from_tensor_slices
    return TensorSliceDataset(tensors)
  File "/home/peng/anaconda3/lib/python3.7/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 2221, in __init__
    tensors = structure_lib.normalize_tensors(tensors)
  File "/home/peng/anaconda3/lib/python3.7/site-packages/tensorflow/python/data/util/structure.py", line 306, in normalize_tensors
    prepared.append(ops.convert_to_tensor(t, name="component_%d" % i))
  File "/home/peng/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 1087, in convert_to_tensor
    return convert_to_tensor_v2(value, dtype, preferred_dtype, name)
  File "/home/peng/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 1145, in convert_to_tensor_v2
    as_ref=False)
  File "/home/peng/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 1224, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/home/peng/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/constant_op.py", line 305, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)
  File "/home/peng/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/constant_op.py", line 246, in constant
    allow_broadcast=True)
  File "/home/peng/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/constant_op.py", line 284, in _constant_impl
    allow_broadcast=allow_broadcast))
  File "/home/peng/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/tensor_util.py", line 475, in make_tensor_proto
    _GetDenseDimensions(values)))
ValueError: Argument must be a dense tensor: [array([0.        , 0.        , 0.        , 0.        , 0.        ,

**Comment by stijani** [comment]
This issue was resolved after the user switched their environment to tensorflow 2.2.
